# Site Settings
title: Resume
url: 'http://vibhoo.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6

#Profile information
name: Vibhoo Mishra
tagline: Software Developer Engineer
pic: profile2.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Exp. web developer with demonstrated skill in developing the product from scratch and scaling the product. Seeking a quality environment where my knowledge and experience can be shared and enriched.'

#sidebar links
email: vibhoo.mishra04@gmail.com
phone: 09454324208
#website: blog.webjeda.com #do not add http://
linkedin: vibhoo
github: vibhoo
bitbucket: vibhoo
twitter: '@vibhoo'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
